# Generated by Django 6.0.4 on 2026-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_update_report_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REPORTED', 'Reported'), ('VERIFIED', 'Verified'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=20),
        ),
    ]
