# Generated by Django 5.2.3 on 2026-04-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_created_at_report_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFIED', 'Verified'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=20),
        ),
    ]
