# Generated by Django 5.2.3 on 2026-04-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('INFRASTRUCTURE', 'Infrastruktur'), ('SECURITY', 'Keamanan'), ('HEALTH', 'Kesehatan'), ('ENVIRONMENT', 'Lingkungan')], default='ENVIRONMENT', max_length=100),
        ),
    ]
